#!/usr/bin/env bash

TAP_POSTGRES_HOST=${TAP_POSTGRES1_HOST}
TAP_POSTGRES_PORT=${TAP_POSTGRES1_PORT}
TAP_POSTGRES_USER=${TAP_POSTGRES1_USER}
TAP_POSTGRES_PASSWORD=${TAP_POSTGRES1_PASSWORD}
TAP_POSTGRES_DB=${TAP_POSTGRES1_DB}

. ${PIPELINEWISE_HOME}/sh/tap_postgres_db.sh

TAP_POSTGRES_HOST=${TAP_POSTGRES2_HOST}
TAP_POSTGRES_PORT=${TAP_POSTGRES2_PORT}
TAP_POSTGRES_USER=${TAP_POSTGRES2_USER}
TAP_POSTGRES_PASSWORD=${TAP_POSTGRES2_PASSWORD}
TAP_POSTGRES_DB=${TAP_POSTGRES2_DB}

. ${PIPELINEWISE_HOME}/sh/tap_postgres_db.sh

TAP_POSTGRES_HOST=${TAP_POSTGRES3_HOST}
TAP_POSTGRES_PORT=${TAP_POSTGRES3_PORT}
TAP_POSTGRES_USER=${TAP_POSTGRES3_USER}
TAP_POSTGRES_PASSWORD=${TAP_POSTGRES3_PASSWORD}
TAP_POSTGRES_DB=${TAP_POSTGRES3_DB}

. ${PIPELINEWISE_HOME}/sh/tap_postgres_db.sh

TAP_POSTGRES_HOST=${TAP_POSTGRES4_HOST}
TAP_POSTGRES_PORT=${TAP_POSTGRES4_PORT}
TAP_POSTGRES_USER=${TAP_POSTGRES4_USER}
TAP_POSTGRES_PASSWORD=${TAP_POSTGRES4_PASSWORD}
TAP_POSTGRES_DB=${TAP_POSTGRES4_DB}

. ${PIPELINEWISE_HOME}/sh/tap_postgres_db.sh

. ${PIPELINEWISE_HOME}/sh/target_postgres.sh
