default:
  outputs:

    dev:
      type: postgres
      host: "{{ env_var( 'TARGET_POSTGRES_HOST' ) }}"
      user: "{{ env_var( 'TARGET_POSTGRES_USER' ) }}"
      password: "{{ env_var( 'TARGET_POSTGRES_PASSWORD' ) }}"
      port: "{{ env_var( 'TARGET_POSTGRES_PORT' ) | as_number }}"
      dbname: "{{ env_var( 'TARGET_POSTGRES_DB' ) }}"
      schema: "{{ env_var( 'TARGET_POSTGRES_SCHEMA' ) }}"
      threads: "{{ env_var( 'TARGET_POSTGRES_THREADS' ) | as_number }}"

    prod:
      type: postgres
      host: "{{ env_var( 'TARGET_POSTGRES_HOST' ) }}"
      user: "{{ env_var( 'TARGET_POSTGRES_USER' ) }}"
      password: "{{ env_var( 'TARGET_POSTGRES_PASSWORD' ) }}"
      port: "{{ env_var( 'TARGET_POSTGRES_PORT' ) | as_number }}"
      dbname: "{{ env_var( 'TARGET_POSTGRES_DB' ) }}"
      schema: "{{ env_var( 'TARGET_POSTGRES_SCHEMA' ) }}"
      threads: "{{ env_var( 'TARGET_POSTGRES_THREADS' ) | as_number }}"

  target: dev
